development:
  adapter: postgresql 
  database: db/console_timecard_development
  pool: 5
  timeout: 5000
#  adapter: sqlite3
#  database: db/development.sqlite3

test:
  adapter: postgresql 
  database: db/console_timecard_test
  pool: 5
  timeout: 5000
#  adapter: sqlite3
#  database: db/test.sqlite3

production:
  adapter: postgresql 
  database: db/console_timecard_production
  pool: 5
  timeout: 5000
